### ISSUE TITLE
Stop assigning work to agents when imageID in profile does not exist in OpenStack

### ISSUE THREAD

**Issue by chrislovsund** [gocd-contrib/openstack-elastic-agent#15]
We have found a bug where GoCD stops assigning work to agents when imageID in profile does not exist in OpenStack. It should at least continue matching agents and jobs.

```
java.lang.RuntimeException: Interaction with plugin with id 'cd.go.contrib.elastic-agent.openstack' implementing 'elastic-agent' extension failed while requesting for 'cd.go.elastic-agent.create-agent'. Reason: [java.lang.RuntimeException: Failed to find image centos7]
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:57)
	at com.thoughtworks.go.plugin.access.elastic.v3.ElasticAgentExtensionV3.createAgent(ElasticAgentExtensionV3.java:101)
	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentExtension.createAgent(ElasticAgentExtension.java:68)
	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentPluginRegistry.createAgent(ElasticAgentPluginRegistry.java:41)
	at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:32)
	at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:22)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to find image centos7
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:221)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:202)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:140)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:48)
	... 8 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to find image centos7
	at cd.go.contrib.elasticagents.openstack.OpenStackPlugin.handle(OpenStackPlugin.java:85)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:143)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:219)
	... 11 common frames omitted
Caused by: java.lang.RuntimeException: Failed to find image centos7
	at cd.go.contrib.elasticagents.openstack.utils.OpenstackClientWrapper.getImageId(OpenstackClientWrapper.java:82)
	at cd.go.contrib.elasticagents.openstack.executors.CreateAgentRequestExecutor.execute(CreateAgentRequestExecutor.java:72)
	at cd.go.contrib.elasticagents.openstack.OpenStackPlugin.handle(OpenStackPlugin.java:63)
	... 13 common frames omitted
```

**Comment by chrislovsund** [comment]
Working on a bug fix now.

**Comment by chrislovsund** [comment]
The fix is working in our PROD environment.

**Comment by tomzo** [comment]
Released in https://github.com/gocd-contrib/openstack-elastic-agent/releases/tag/0.12.0
